baseURL = "https://hugoblog-swart.vercel.app"
languageCode = "en-us"
title = "Daylen's Blog"
theme = "paper"

[params]
  avatar = 'stussury@gmail.com'                 # gravatar email or image url
  name = 'DaylenJeez'
  bio = 'Still you gotta rise'

[menu]

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
tag = "tags"
